
option(ENABLE_DAPR "enable dapr")
if (ENABLE_DAPR)
  option(protobuf_BUILD_TESTS "test opiton" off)
  set(OPENSSL_NO_ASM "1")
  set(protobuf_BUILD_EXAMPLES OFF)
  # add_subdirectory(amqp_test)
  add_subdirectory(third-party/grpc)
  add_subdirectory(third-party/dapr)
else()
  find_package(ZLIB REQUIRED)
  find_package(CURL CONFIG REQUIRED)
  find_package(asio CONFIG REQUIRED)
  find_package(amqpcpp CONFIG REQUIRED)
  find_package(Protobuf CONFIG REQUIRED)
endif(ENABLE_DAPR)