________________________________________
[您的姓名] | +86 XXX-XXXX-XXXX | your.email@example.com | [求职意向城市] | [GitHub/LinkedIn/技术博客(选填)]

**求职意向：** 高级软件工程师 / BIM软件开发工程师 / 三维图形系统开发工程师

**专业技能**
*   **核心语言 & 框架：** 
    *   **C++**：精通标准库(STL)、Boost库、精通MFC框架开发、熟练运用Qt框架进行跨平台GUI及核心模块开发。
    *   **Python**: 掌握，用于脚本工具开发、自动化测试、数据处理及算法原型验证。
    *   **C#/.NET**: 掌握，主要用于CAD/BIM平台二次开发(如AutoCAD/Revit API)。
    *   **VB**: 熟悉（鉴于其在历史工程软件中的存在）。
*   **三维图形与建模：**
    *   深入理解三维图形学原理(几何变换、渲染管线、网格处理)。
    *   熟练掌握三维模型构建、操作、渲染技术 (OpenGL/DirectX 基础)。
    *   精通参数化建模逻辑，熟悉BIM数据标准(IFC等)。
*   **软件开发相关：**
    *   软件架构设计能力：具备设计复杂、可维护、可扩展应用架构的能力。
    *   面向对象设计与设计模式：深刻理解并实践SOLID原则及常用设计模式。
    *   数据结构与算法：扎实的基础，解决复杂工程计算问题的能力。
    *   版本控制：熟练使用Git/SVN。
    *   工程软件对接：熟悉AutoCAD、Revit、Tekla Structures等平台二次开发接口。
*   **领域知识：** 深厚的土木工程专业知识背景，理解桥梁建筑结构设计、施工流程和关键问题。
*   **其他工具：** CMake, Visual Studio, PyCharm, 单元测试框架等。

**工作经验**
**[公司名称] | BIM/桥梁建模软件开发工程师** | [城市] | [起止年月 - 至今/离职年月]
*   **面向土木工程的专业软件开发：** 
    *   主导/参与开发用于桥梁与建筑的三维BIM建模软件核心模块，**使用 C++ (MFC/Qt)** 实现高精度几何建模、结构计算可视化及复杂构件参数化生成逻辑。
    *   设计并实现 **BIM模型数据结构与算法**，高效管理数百万级构件信息，优化模型查询与操作性能，**处理模型加载速度提升XX%**。
    *   实现自动化施工图生成功能，**利用 C++/Python** 解析设计模型数据，驱动CAD引擎(AutoCAD API)，**显著减少人工绘图错误，图纸生产效率提高XX%**。
    *   开发 **BIM模型检查与规则校验插件 (C#/.NET + Revit API)**，识别并预警设计冲突与规范违规问题，**帮助项目平均缩短XX天的设计审核时间**。
*   **架构与技术方案：**
    *   负责核心框架选型与技术栈定义，如基于Qt重构传统MFC应用以提升跨平台能力和用户体验。
    *   解决大规模三维模型渲染性能瓶颈，通过空间索引优化、LOD技术应用等**提升复杂场景渲染帧率至XX FPS以上**。
*   **项目支持：** 为项目团队提供高级技术支持，解决设计与施工中遇到的模型软件技术难题。

**[公司名称] | 软件开发工程师** | [城市] | [起止年月 - 离职年月]
*   （可简述前期积累经验，重点描述与后续BIM/工程相关的技术积累）

**项目经历 (选择最具代表性和价值的2-3个项目)**
**[项目名称]： [某大型桥梁/建筑] BIM建模与施工图一体化系统开发**
*   **角色：** 核心架构师 / 主要开发人员 / 技术负责人 (据实填写)
*   **技术栈:** C++ (Qt + Boost), Python, AutoCAD API
*   **挑战与解决方案：**
    *   针对XX大型斜拉桥，**开发基于C++的高效参数化主梁建模引擎**，支持复杂空间曲面构造，精度满足施工要求。
    *   集成有限元计算结果，**实现荷载作用下的结构变形可视化动态模拟 (OpenGL)**。
    *   **设计自动化出图流程**：由模型数据驱动，利用Python脚本批量调用AutoCAD API，**自动生成XX类型施工图纸(如配筋图、构造图)，减少人工工时约XX%**。
    *   **开发模型转换工具**，实现内部模型与IFC格式的双向转换，提升数据互操作性。
*   **成果：** 成功应用于XX实际工程项目，提升设计协同效率约XX%，图纸规范性提高XX%。

**[项目名称]： [某类建筑] 精细化机电管线碰撞检查与施工模拟工具**
*   **角色：** 软件开发主管 / 主程
*   **技术栈:** C#/.NET (Revit API), Python, Boost Geometry
*   **挑战与解决方案：**
    *   **基于Revit API开发高效碰撞检测算法核心(C#)**，利用空间划分策略 (如Octree) 和Boost.Geometry库处理复杂几何体碰撞。
    *   **集成进度管理数据**，开发4D施工模拟模块(Python + 可视化引擎)，模拟安装顺序冲突。
    *   **开发用户交互友好的报告系统**，精确定位碰撞点并生成可视化报告。
*   **成果：** 在XX超高层项目中，**提前发现并解决XXX处碰撞点，避免返工损失估算达XXX万元**。

**教育背景**
**[大学名称] | [城市] | [起止年月]**
*   土木工程 学士学位 (或其他相关学位)
*   *(可选，如成绩优异或与软件开发相关)*：主修课程：结构力学、材料力学、桥梁工程、计算机辅助设计等
    *(突出您工程背景的价值)*

**证书与荣誉 (选填)**
*   (如有相关认证，如：) BIM 一级/二级建模师 (可选，虽偏向应用，但证明了解流程)、微软认证等。
*   (含金量高的技术类或工程类奖项)

**自我评价/技术总结 (强烈建议添加)**
> 兼具 **深厚土木工程底蕴 (8年经验)** 与 **精湛软件开发技能** 的复合型高级工程师。专注于将工程知识转化为高效、可靠的工业软件解决方案。**精通C++ (STL/Boost/MFC/QT)架构设计**，具备构建大型三维BIM建模与施工图系统的能力，**熟练运用Python、C#**解决工程软件自动化及平台集成问题。追求在图形计算、BIM核心平台开发领域持续深耕，致力于通过技术创新提升工程建设效率与质量。
