function(ds_source_group_by_dir source_files)
  if(MSVC)
    set(ds_cur_dir ${CMAKE_CURRENT_SOURCE_DIR})
    foreach(ds_file ${${source_files}})
      string(REGEX REPLACE ${ds_cur_dir}/\(.*\) \\1 ds_fpath ${ds_file})
      string(REGEX REPLACE "\(.*\)/.*" \\1 ds_group_name ${ds_fpath})
      string(COMPARE EQUAL ${ds_fpath} ${ds_group_name} ds_nogroup)
      string(REPLACE "/" "\\" ds_group_name ${ds_group_name})
      if(ds_nogroup)
        set(ds_group_name "\\")
      endif(ds_nogroup)
      source_group(${ds_group_name} FILES ${ds_file})
    endforeach(ds_file)
  endif(MSVC)
endfunction(ds_source_group_by_dir)